export const vietnamBanks = [
  'Vietcombank',
  'BIDV',
  'VietinBank',
  'Agribank',
  'MB Bank',
  'Techcombank',
  'ACB',
  'VPBank',
  'TPBank',
  'Sacombank',
  'HDBank',
  'VIB',
  'SHB',
  'OCB',
  'MSB',
  'SeABank',
  'Eximbank',
  'LPBank',
  'PVcomBank',
  'SCB',
  'Nam A Bank',
  'ABBank',
  'Bac A Bank',
  'BaoViet Bank',
  'BVBank',
  'KienlongBank',
  'NCB',
  'PGBank',
  'Saigonbank',
  'VietABank',
  'VietBank',
  'GPBank',
  'OceanBank',
  'CBBank',
  'Co-opBank',
  'Shinhan Bank Vietnam',
  'Woori Bank Vietnam',
  'HSBC Vietnam',
  'Standard Chartered Vietnam',
  'UOB Vietnam',
  'CIMB Vietnam',
  'Public Bank Vietnam',
  'Hong Leong Bank Vietnam',
  'Indovina Bank',
  'Vietnam-Russia Joint Venture Bank (VRB)',
  'Cake by VPBank',
  'Timo by BVBank',
  'TNEX by MSB',
]
